## Mathematical Computation with Numpy 

Numpy offers comprehensive mathematical functions, 
random number generators, linear algebra routines, Fourier transforms, and more. 


Main numpy website is the following:
    
https://numpy.org/
    
You can find numpy tutorial and documentations here 

https://numpy.org/doc/stable/

If you are new to numpy, then start with the following quick start guide 

https://numpy.org/doc/stable/user/quickstart.html
    
    

In [1]:
# first install and import the numpy 

# if you have not installed it already, you can use pip install to do it. 

!pip install numpy

# You only need to install it once on your machine. Comment out the above line if you have already installed numpy. 
# Then import it
import numpy  as np


# Create a Numpy Array

A very simple array:

In [2]:
a = np.array([0,1,2,3])
print(a)

[0 1 2 3]


Find out the size of the a numpy array using .size attribute. 


In [3]:
size = a.size

# Then print it to show
print(size)

4


# Ndim – number of dimensions


In [4]:
a.ndim

1

# Shape of Array

Find out what is the shape of this Array "a"

Shape returns a tuple listing the length of array along each dimension of it

In [5]:
# a.shape
(4,)


(4,)

# Type 
You can always use type() function in Python to find out the type of an object 

In [6]:
type(a)

numpy.ndarray

# Type of Elements of an Array

In [7]:
# Type of Elements:
a.dtype


dtype('int64')

# Bytes per Elements


In [8]:
 a.itemsize

8

# Bytes of the entire array

.nbytes returns the number of bytes

In [9]:
a.nbytes

32

# Creating an Array including booleans

In [10]:
b = np.array([True, False, True, False], dtype=bool)
b

array([ True, False,  True, False])

In [11]:
b.dtype

dtype('bool')

In [12]:
b.nbytes

4

# Creating Array from range of numbers (arange)

In [13]:
np.arange(3)

array([0, 1, 2])

In [14]:
np.arange(3.0)

array([0., 1., 2.])

In [15]:
np.arange(3,7)

array([3, 4, 5, 6])

In [16]:
# Step size 2 
np.arange(3,7,2)

array([3, 5])

# Read the Manual for each function 

numpy.arange([start, ] stop, [step, ]dtype=None)

Here 

https://numpy.org/doc/stable/reference/generated/numpy.arange.html

In [17]:
# It is easier to call the help() function
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.
    
    Parameters
    ----------
    start : number, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : number
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off affects the length of `out`.
   

# Creating Arrays - np.linspace()

Evenly spaced numbers with careful handling of endpoints.

In [18]:
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [19]:
np.linspace(2.0, 3.0, num=5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [20]:
np.linspace(2.0, 3.0, num=5, retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

In [21]:
# numpy.linspace (start, stop, num=50, endpoint=True, retstep=False, dtype=None)

help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num : int, optional
        Number of samples to generate. Default is 50. Must be non-negative.
    endpoint : bool, optional
        If True, `stop` is

# Operations on Arrays 

Simple Array Operations, like addition of two arrays 

In [22]:
a =np.arange(1,5)
b =np.array([1,1,1,1])

c = a + b 
print(a)
c


[1 2 3 4]


array([2, 3, 4, 5])

## Simple Element-wise Array Multiplication using * operator

In [23]:
c= a * a 
c

array([ 1,  4,  9, 16])

In [24]:
# Element-wise power operation using **

c = a ** a 

c

array([  1,   4,  27, 256])

In [25]:
# Simple Math Functions like np.sin()
y = np.sin(a)
y

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [26]:
# see 

help(np.sin)

Help on ufunc object:

sin = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  Calling ufuncs:
 |  ===============
 |  
 |  op(*x[, out], where=True, **kwargs)
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array o

In [27]:
# NumPy defines PI and e constants:
# pi = 3.141592653589793 ... 
# e = 2.718281828459045 ... 

np.pi

3.141592653589793

In [28]:
np.e

2.718281828459045

In [29]:
c = (2* np.pi)*a
c

array([ 6.28318531, 12.56637061, 18.84955592, 25.13274123])

# In-place operations


# What is in-place?
If you want to apply mathematical operations to a numpy array in-place, 
you can simply use the standard in-place operators +=, -=, /=, etc. So for example:


In [30]:
# Let us define a function add_10
def add_10(a):
    a += 10

a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
add_10(a)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

## Another Inplace Example

In [32]:
x= np.arange(6.0)
z = 2*np.pi
x*=z 
x

array([ 0.        ,  6.28318531, 12.56637061, 18.84955592, 25.13274123,
       31.41592654])

# Setting Array Elements – Filling Arrays 

In [33]:
## Indexing 
a = np.arange(1,5, dtype=float)
a[0]

1.0

In [34]:
## Seting values
a[0]= 2*np.pi
a

array([6.28318531, 2.        , 3.        , 4.        ])

## Fill - Fill the array with a scalar value.

In [35]:
a.fill(0)
a

array([0., 0., 0., 0.])

In [36]:
a.fill(2.3)
a

array([2.3, 2.3, 2.3, 2.3])

# Create Arrays with ones and Zeros

In [37]:
x=np.zeros(5)
x

array([0., 0., 0., 0., 0.])

In [38]:
x=np.ones(5)
x

array([1., 1., 1., 1., 1.])

In [39]:
# Multi-Dimentional
np.ones([3, 2, 2])

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

# Array Slicing 

Slicing  can extract a portion of an array by using  a lower and upper bound. 

var[lower:upper:step]



In [40]:
a[1:3]

array([2.3, 2.3])

In [41]:
# Filling by using slice
a[1:3]=1
a

array([2.3, 1. , 1. , 2.3])

## Negative Indexes

In [42]:
print(a)
a[1:-2]

[2.3 1.  1.  2.3]


array([1.])

In [43]:
a[-3:-1]

array([1., 1.])

# Omitting indices

Start or end or both

In [44]:
print(a)
a[:2]

[2.3 1.  1.  2.3]


array([2.3, 1. ])

In [45]:
a[-2:]

array([1. , 2.3])

# Slicing with steps

In [46]:
print(a)
a[::2]

[2.3 1.  1.  2.3]


array([2.3, 1. ])

In [47]:
a[1::2]

array([1. , 2.3])

In [48]:
# Get elements with even indexes
a[::2]

array([2.3, 1. ])

In [49]:
# Get elements with odd indexes
a[1::2]

array([1. , 2.3])

# Slices are References

Slices are simple references to the original memory. Any changes on the slices would change the original array. 

In [50]:
a = np.arange(1,6)
a

array([1, 2, 3, 4, 5])

In [51]:
b = a[2:4]
b

array([3, 4])

In [52]:
b[0] = 100
a

array([  1,   2, 100,   4,   5])

In [53]:
# N-Dimensional Arrays

b = np.array([[ 10, 11, 12, 13], [20, 21, 22, 23]])
b


array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [54]:
b.shape

(2, 4)

In [55]:
b.size

8

In [56]:
b.ndim

2

# Indexing in 2-D

In [57]:
print(b)
b[1,3]

[[10 11 12 13]
 [20 21 22 23]]


23

In [58]:
b[1,3]=2.3
b

array([[10, 11, 12, 13],
       [20, 21, 22,  2]])

## Addressing the rows using single index 

In [59]:
print(b)
b[1]

[[10 11 12 13]
 [20 21 22  2]]


array([20, 21, 22,  2])

## Multidimensional  Array Slicing

In [60]:
# Similar to 1-D
c= np.array([np.arange(10,14), np.arange(20,24), np.arange(30,34), np.arange(40,44)])
c

array([[10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [61]:
c.shape

(4, 4)

In [62]:
c[1:3]

array([[20, 21, 22, 23],
       [30, 31, 32, 33]])

In [63]:
# Addressing a column
c[:,2]

array([12, 22, 32, 42])

In [64]:
# Addressing with steps 
c[2::2, ::2]

array([[30, 32]])

# Advanced indexing

In [65]:
a = np.arange(10,40,2)
a

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [66]:
# Use another numpy as index to address 
indexes=np.array([1,3,-4])
x=a[indexes]
x

array([12, 16, 32])

# Indexing with Booleans

In [67]:
a = np.arange(10,60,10)
print(a)
my_mask=np.array([1,0,1,1,1],dtype="bool")
print(my_mask)

y = a[my_mask]
y

[10 20 30 40 50]
[ True False  True  True  True]


array([10, 30, 40, 50])

# Create a mask by condition

In [68]:
# Use a conditional statment to create a mask
my_mask2= a < 20

my_mask2

array([ True, False, False, False, False])

In [69]:
y=a[my_mask2]

y

array([10])

# Reshaping  Arrays

In [70]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
a.shape

(10,)

In [72]:
a.shape=(2,1,5)
a

array([[[0, 1, 2, 3, 4]],

       [[5, 6, 7, 8, 9]]])

# Reshape
Reshape – Returns a new array from the original array

In [73]:
b=a.reshape(5,2)
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

# Reshape does not remove elements
It means the new shape dimensions should match, i.e., you can not do the following
a.reshape(3,3) because the new dimensions does not match. 

# Flatten Arrays and Flat Attribute

In [74]:
a=np.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
b=a.reshape(5,2)
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [76]:
c=b.flatten()
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Attribute – flat 

a.flat is an attribute that can be used like an iterator to access elements in a N-D array as one dimensional array.

In [77]:
d=a.flat
d

In [78]:
d[2]=100
a

array([  0,   1, 100,   3,   4,   5,   6,   7,   8,   9])

# Where Method - Finding Indexes

np.where() finds indexes in array where expression is True. 

In [79]:
a =  np.array([ 1.19,  2.42,  3.91,  4.66])
a>2

array([False,  True,  True,  True])

In [80]:
np.where(a>2)

(array([1, 2, 3]),)

## Where 2D

In [81]:
a= np.arange(0,8).reshape(2,4)
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [82]:
a>2

array([[False, False, False,  True],
       [ True,  True,  True,  True]])

In [83]:
help(np.where)

Help on function where in module numpy:

where(...)
    where(condition, [x, y])
    
    Return elements chosen from `x` or `y` depending on `condition`.
    
    .. note::
        When only `condition` is provided, this function is a shorthand for
        ``np.asarray(condition).nonzero()``. Using `nonzero` directly should be
        preferred, as it behaves correctly for subclasses. The rest of this
        documentation covers only the case where all three arguments are
        provided.
    
    Parameters
    ----------
    condition : array_like, bool
        Where True, yield `x`, otherwise yield `y`.
    x, y : array_like
        Values from which to choose. `x`, `y` and `condition` need to be
        broadcastable to some shape.
    
    Returns
    -------
    out : ndarray
        An array with elements from `x` where `condition` is True, and elements
        from `y` elsewhere.
    
    See Also
    --------
    choose
    nonzero : The function that is called when x and y

In [84]:
mindex=np.where(a>2)
mindex

(array([0, 1, 1, 1, 1]), array([3, 0, 1, 2, 3]))

In [85]:
y=a[mindex]
y

array([3, 4, 5, 6, 7])

# Array Operation
Linear Alegra Operation



## Array Transpose

In [86]:
a=np.arange(0,10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [87]:
a.transpose()

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [88]:
# You can also access it as attribute
a.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

## Strides
* Strides are Tuple of bytes to step in each dimension
* 8 bytes (1 value) to move to the next column, but 40 bytes (5 values) to get to the same position in the next row.
* Transpose only changes the values of "Strides" in the array memory. 


In [89]:
a.strides

(40, 8)

In [90]:
a.T.strides

(8, 40)

# Sum Operation 
np.sum() – sum up the elements


In [91]:
a=np.arange(100)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [92]:
np.sum(a)

4950

## Sum along the  axis

In [93]:
a=np.arange(0,10).reshape(5,2)
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [94]:
np.sum(a, axis=0)

array([20, 25])

In [95]:
np.sum(a, axis=1)

array([ 1,  5,  9, 13, 17])

# Product – calculate product of columns


In [96]:
a=np.arange(0,10).reshape(5,2)
a 

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [97]:
a.prod(axis=0)

array([  0, 945])

In [98]:
a.prod(axis=1)

array([ 0,  6, 20, 42, 72])

## Matrix Multiplication
np.matmul()


In [99]:
a = np.array([[1, 0],
              [0, 1]])

b = np.array([[4, 1],
              [2, 2]])
np.matmul(a, b)

array([[4, 1],
       [2, 2]])

In [100]:
help(np.matmul)

Help on ufunc object:

matmul = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  Calling ufuncs:
 |  ===============
 |  
 |  op(*x[, out], where=True, **kwargs)
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate arra

## Dot Product 

In [101]:
a=np.arange(0,16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [102]:
b=np.array([2,5,1,9])
b

array([2, 5, 1, 9])

In [103]:
np.dot(a, b)

array([ 34, 102, 170, 238])

In [104]:
np.dot(b,b)

111

## Minimum and Maximum 

In [105]:
a=np.arange(0,10).reshape(5,2)
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [106]:
a.min(axis=0)

array([0, 1])

In [107]:
a.max(axis=1)

array([1, 3, 5, 7, 9])

# argmin – finding the index of Minimum element

In [108]:
help(np.argmin)

Help on function argmin in module numpy:

argmin(a, axis=None, out=None)
    Returns the indices of the minimum values along an axis.
    
    Parameters
    ----------
    a : array_like
        Input array.
    axis : int, optional
        By default, the index is into the flattened array, otherwise
        along the specified axis.
    out : array, optional
        If provided, the result will be inserted into this array. It should
        be of the appropriate shape and dtype.
    
    Returns
    -------
    index_array : ndarray of ints
        Array of indices into the array. It has the same shape as `a.shape`
        with the dimension along `axis` removed.
    
    See Also
    --------
    ndarray.argmin, argmax
    amin : The minimum value along a given axis.
    unravel_index : Convert a flat index into an index tuple.
    take_along_axis : Apply ``np.expand_dims(index_array, axis)`` 
                      from argmin to an array as if by calling min.
    
    Notes
    ---

In [109]:
a.argmin(axis=1)

array([0, 0, 0, 0, 0])

In [110]:
a.argmin(axis=0)

array([0, 0])

Maximum is simalar to above 

# Statistics Array Methods

## Mean

In [111]:
a=np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [112]:
a.mean(axis=0)

array([4., 5., 6.])

In [113]:
# Similar to above is the function average()
np.average(a, axis=0)

array([4., 5., 6.])

## Standard Deviation

In [114]:
print(a)
a.std(axis=0)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([2.44948974, 2.44948974, 2.44948974])

In [115]:
 a.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

## Variance

In [116]:
a.var(axis=0)

array([6., 6., 6.])

In [117]:
a.var(axis=1)

array([0.66666667, 0.66666667, 0.66666667])

#  Further Useful Numpy Array Methods

## clip() 
limit the values in an array


In [118]:
a=np.arange(20,29)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28])

Consider the following two situations:
1. set values less than 22 to 22
2. set values bigger than 27 to 27

In [119]:
a.clip(22,27)

array([22, 22, 22, 23, 24, 25, 26, 27, 27])

In [120]:
# Read more about clip()
help(np.clip)

Help on function clip in module numpy:

clip(a, a_min, a_max, out=None, **kwargs)
    Clip (limit) the values in an array.
    
    Given an interval, values outside the interval are clipped to
    the interval edges.  For example, if an interval of ``[0, 1]``
    is specified, values smaller than 0 become 0, and values larger
    than 1 become 1.
    
    Equivalent to but faster than ``np.maximum(a_min, np.minimum(a, a_max))``.
    No check is performed to ensure ``a_min < a_max``.
    
    Parameters
    ----------
    a : array_like
        Array containing elements to clip.
    a_min : scalar or array_like or None
        Minimum value. If None, clipping is not performed on lower
        interval edge. Not more than one of `a_min` and `a_max` may be
        None.
    a_max : scalar or array_like or None
        Maximum value. If None, clipping is not performed on upper
        interval edge. Not more than one of `a_min` and `a_max` may be
        None. If `a_min` or `a_max` are ar

## Peak to Peak 
Range of values (maximum - minimum) along an axis.

In [121]:
a=np.array([[1,4,5,9], [2,9,8,1]])
print(a)
a.ptp(axis=0)
# From 1 to 2 distance is 1
# From 4 to 9 distance is 5
# From 5 to 8 distance is 3
# From 9 to 1 distance is 8

[[1 4 5 9]
 [2 9 8 1]]


array([1, 5, 3, 8])

In [122]:
a.ptp(axis=1)

array([8, 8])

In [123]:
# Read more in manual documentation
help(np.ptp)

Help on function ptp in module numpy:

ptp(a, axis=None, out=None, keepdims=<no value>)
    Range of values (maximum - minimum) along an axis.
    
    The name of the function comes from the acronym for 'peak to peak'.
    
    Parameters
    ----------
    a : array_like
        Input values.
    axis : None or int or tuple of ints, optional
        Axis along which to find the peaks.  By default, flatten the
        array.  `axis` may be negative, in
        which case it counts from the last to the first axis.
    
        .. versionadded:: 1.15.0
    
        If this is a tuple of ints, a reduction is performed on multiple
        axes, instead of a single axis or all the axes as before.
    out : array_like
        Alternative output array in which to place the result. It must
        have the same shape and buffer length as the expected output,
        but the type of the output values will be cast if necessary.
    
    keepdims : bool, optional
        If this is set to True, 

# Some good Tutorials on Conferences 

SciPy Conference 2019, like 
https://www.scipy2019.scipy.org/ in Austin

https://www.youtube.com/watch?v=ZB7BZMhfPgk 
    